CREATE TABLE users
(
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(68) NOT NULL,
    ENABLED  BOOLEAN     NOT NULL,
    PRIMARY KEY (USERNAME)
);

INSERT INTO users (USERNAME, PASSWORD, ENABLED)
VALUES ('employee', '$2a$10$cRqfrdolNVFW6sAju0eNEOE0VC29aIyXwfsEsY2Fz2axy3MnH8ZGa', true);
INSERT INTO users (USERNAME, PASSWORD, ENABLED)
VALUES ('manager', '$2a$10$cRqfrdolNVFW6sAju0eNEOE0VC29aIyXwfsEsY2Fz2axy3MnH8ZGa', true);

CREATE TABLE authorities
(
    USERNAME  VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(68) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES users (USERNAME)
);

INSERT INTO authorities
VALUES ('employee', 'ROLE_EMPLOYEE');
INSERT INTO authorities
VALUES ('employee', 'ROLE_USER');
INSERT INTO authorities
VALUES ('manager', 'ROLE_MANAGER');
INSERT INTO authorities
VALUES ('manager', 'ROLE_USER');